data_format: 'yaml'

custom_data:
    sequencing_stats:
        parent_id: sequence_analysis
        parent_name: "Sequence Analysis"
        parent_description: ""
        id: 'sequencing_stats'
        section_name: 'Physico-chemical properties'
        plot_type: 'table'
        pconfig:
            id: 'sequencing_stats_plot'
            namespace: 'Sequence properties'
            format: '{:,.2f}'
            table_title: 'Sequence properties'
            max: 0
            min: 0
        headers:
            Molecular weight:
                description: "Molecular weight(g/mol)."
            Atoms:
                description: "Total number of atoms."
                format: '{:,.0f}'
            Aromaticity:
                description: "Aromaticity according to Lobry, 1994.(relative frequency of Phe+Trp+Tyr)"
            Instability index:
                description: "Instability index according to Guruprasad et al 1990."
            Isoelctric point:
                description: "Isoelectric point."
            Extinction coefficients:
                description: "The molar extinction coefficient assuming cysteines (reduced) and cystines residues (Cys-Cys-bond)"
            GRAVY:
                description: "Grand average of hydropathicity index(Gravy) according to Kyte and Doolittle."
            Negatively charged residues:
                description: "Total number of negatively charged residues (Asp + Glu)."
                format: '{:,.0f}'
            Positively charged residues:
                description: "Total number of positively charged residues (Arg + Lys)."
                format: '{:,.0f}'
    
    aa:
        parent_id: sequence_analysis
        parent_name: "Sequence Analysis"
        parent_description: ""
        id: 'aa'
        section_name: 'Amino acid composition'
        plot_type: 'bargraph'
        pconfig:
            id: 'aa_plot'
            height: '450' 
        
    atom_count:
        parent_id: sequence_analysis
        parent_name: "Sequence Analysis"
        parent_description: ""
        id: 'atom_count'
        section_name: 'Atom composition'
        plot_type: 'bargraph'
        pconfig:
            id: 'atom_count_plot'
            height: '200' 
        
    ph:
        parent_id: sequence_analysis
        parent_name: "Sequence Analysis"
        parent_description: ""
        id: 'ph'
        section_name: 'Charge at pH'
        plot_type: 'linegraph'
        pconfig:
            id: 'ph_plot'
            namespace: 'Charge at pH'
            xlab: 'pH'
            ylab: 'charge'
            height: '250'
            tt_label: '{point.x:.2f}: {point.y:.4f}'

    flex:
        parent_id: sequence_analysis
        parent_name: "Sequence Analysis"
        parent_description: ""
        id: 'flex'
        section_name: 'Flexibility'
        description: 'Vihinen 1994. scale'
        plot_type: 'linegraph'
        pconfig:
            id: 'flex_plot'
            namespace: 'Flexibility'
            title: 'Flexibility scale'
            xlab: 'residue'
            ylab: 'flexibility'
            height: '250'

    hydro:
        parent_id: sequence_analysis
        parent_name: "Sequence Analysis"
        parent_description: ""
        id: 'hydro'
        section_name: 'Hydrophobicity'
        description: 'Kyte&Doolittle scale'
        plot_type: 'linegraph'
        pconfig:
            id: 'hydro_plot'
            namespace: 'Hydrophobicity'
            title: 'Hydrophobicity scale'
            xlab: 'residue'
            ylab: 'Hydrophobicity'
            height: '250'    

    msa:
        parent_id: evolutionary_analysis
        parent_name: 'Evolutionary Analysis'
        parent_description: ''
        id: 'msa'
        section_name: 'MSA - Sequence conservation'
        plot_type: 'linegraph'
        pconfig:
            id: 'msa_plot'
            namespace: 'msa'
            title: 'Sequence Conservation'
            xlab: 'residue'
            ylab: 'Jensen-Shannon divergence'
            height: '250'
            tt_label: '{point.x:.0f}: {point.y:.4f}'


    p2rank:
        parent_id: molecular_docking
        parent_name: "Molecular Docking"
        parent_description: ""
        id: 'p2rank'
        section_name: 'P2Rank - Pocket prediction'
        plot_type: 'table'
        pconfig:
            id: 'p2rank_plot'
            namespace: 'P2Rank'
            format: '{:,.2f}'
            table_title: 'P2Rank'
            max: 0
            min: 0
        headers:
            Rank:
                format: '{:,.0f}'
                description: 'Pocket ranked based on score.'
            Score:
                description: 'Pocket predicted ligandability score.'
            Probability:
                description: 'Probability of being a ligand-binding site.'
            SAS points:
                description: 'Nr. of Solvent Accessible Surface points.'
                format: '{:,.0f}'
            Surface atoms:
                description: 'Nr. of solvent exposed atoms.'
                format: '{:,.0f}'
            Center X:
                description: 'Pocket X coordinate.'
            Center Y:
                description: 'Pocket Y coordinate.'
            Center Z:
                description: 'Pocket Z coordinate.'


sp:
    sequencing_stats:
        fn: 'seq_stats.txt'
    flex:
        fn: 'seq_flexibility.txt'
    hydro:
        fn: 'seq_hydrophobicity.txt'
    ph:
        fn: 'seq_ph.txt'
    aa:
        fn: 'seq_residue_count.txt'
    atom_count:
        fn: 'seq_atom_count.txt'
    msa:
        fn: '*.conservation'
    p2rank:
        fn: 'p2rank_predictions.csv'

report_section_order:
    sequence_analysis:
        order: -100
    protein_sequence:
        order: -101
    evolutionary_analysis:
        order: -200
    pfam:
        order: -202
    pfam:
        order: -201
    structure_analysis:
        order: -300
    protein_structure:
        order: -301
    molecular_docking:
        order: -400
    p2rank:
        order: -409
    pocket_viewer:
        order: -408


table_columns_placement:
    sequencing_stats_plot:
        Molecular weight: 1
        Atoms: 1.5
        Aromaticity: 2
        Instability index: 3
        Isoelctric point: 4
        Extinction coefficients: 5
        Gravy: 6
    p2rank_plot:
        Rank: 1
        Score: 2
        Probability: 3
        SAS points: 4
        Surface atoms: 5
        Center X: 6
        Center Y: 7 
        Center Z: 8
    docking_plot:
        Best Score: 1
        Avg. Score: 2
        Center: 3
        Box Size: 4
        Spacing: 5
        Exhaustiveness: 6